=== lars-reimann/playground/Java/Applications/TowerDefense/data/towers/towerDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT tower (name, price, weapon, upgrades)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT weapon (damage, range, timePerShoot)>
<!ELEMENT upgrades (upgrade)*>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT range (#PCDATA)>
<!ELEMENT timePerShoot (#PCDATA)>
<!ELEMENT upgrade (price, newDamage, newRange, newTimePerShoot)>
<!ELEMENT newDamage (#PCDATA)>
<!ELEMENT newRange (#PCDATA)>
<!ELEMENT newTimePerShoot (#PCDATA)>

=== lars-reimann/playground/Java/TowerDefense/data/towers/turm3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tower SYSTEM "towerDTD.dtd">

<tower>
	<name>turm3</name>
	<price>200</price>
	<weapon>
		<damage>50</damage>
		<range>100</range>
		<timePerShoot>2</timePerShoot>
	</weapon>
	<upgrades>
		<upgrade>
			<price>200</price>
			<newDamage>60</newDamage>
			<newRange>100</newRange>
			<newTimePerShoot>2</newTimePerShoot>
		</upgrade>
		<upgrade>
			<price>400</price>
			<newDamage>70</newDamage>
			<newRange>100</newRange>
			<newTimePerShoot>2</newTimePerShoot>
		</upgrade>
		<upgrade>
			<price>600</price>
			<newDamage>80</newDamage>
			<newRange>100</newRange>
			<newTimePerShoot>1</newTimePerShoot>
		</upgrade>
		<upgrade>
			<price>800</price>
			<newDamage>90</newDamage>
			<newRange>100</newRange>
			<newTimePerShoot>1</newTimePerShoot>
		</upgrade>
		<upgrade>
			<price>1000</price>
			<newDamage>100</newDamage>
			<newRange>100</newRange>
			<newTimePerShoot>1</newTimePerShoot>
		</upgrade>
	</upgrades>
</tower>
